//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriE_commerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVenta
    {
        public int idVenta { get; set; }
        public Nullable<int> proId { get; set; }
        public Nullable<System.DateTime> fechaVenta { get; set; }
        public Nullable<int> cantidadVenta { get; set; }
    
        public virtual tblProducto tblProducto { get; set; }
    }
}
